### PR TITLE
Add README-vi.md for VietNammese Language

### PR DESCRIPTION
**Pull request by conglt10**
I am a Blockchain developer in VietNam. I see your document is very good. I decided to translate overall your document from English to VietNamese. Thank you !

### CODE REVIEW

**Comment by maurelian** [comment]
Hey, sorry for not responding yet. Let me see if I can find someone to give this a quick review just for a sanity check. Thanks!

**Comment by maurelian** [comment]
@conglt10 could you update this to align with #226?

**Comment by conglt10** [comment]
> @conglt10 could you update this to align with #226?

Of course. I have edited README-vi.md follow #226

**Comment by cleanunicorn** [comment]
@conglt10 I was trying to see if the document you created is in line with Readme.md. I do not understand Vietnamese but looking at the code examples, they seem to be very different from the original Readme. 

Is this because of the changes that happened in the meantime or is it something else?

**Comment by conglt10** [comment]
> @conglt10 I was trying to see if the document you created is in line with Readme.md. I do not understand Vietnamese but looking at the code examples, they seem to be very different from the original Readme.
> 
> Is this because of the changes that happened in the meantime or is it something else?

I don't know. I translate from https://consensys.github.io/smart-contract-best-practices/ and i have edited follow #226.

**Comment by maurelian** [comment]
going to merge in #232

**Pull request closed without merging**
