### PR TITLE
Underflow Storage Manipulation Vuln

### PR DESCRIPTION
**Pull request by djphillyg**
Addressed #102 to review and update underhanded solidity winners from this following medium article (https://medium.com/@weka/announcing-the-winners-of-the-first-underhanded-solidity-coding-contest-282563a87079), completed an entry on the Hoyte attack.

### CODE REVIEW

**Comment by mimoo** [comment]
I'd say that falls in the arithmetic and comparisons issues rather than a storage manipulation vuln (which is the impact)

**Comment by maurelian** [comment]
I think we can include this, with a more minimal example.

**Comment by djphillyg** [comment]
Rewrote a more minimal applicable example

**Comment by federicobond** [comment]
`length` is soon becoming read-only, so this may not last much. See  https://github.com/ethereum/solidity/issues/3515

**Comment by maurelian** [comment]
Thanks for the heads up @federicobond :)

**Pull request merged**
