### PR TITLE
Added iterator maximum

### PR DESCRIPTION
**Pull request by nemild**

### CODE REVIEW

**Comment by ethers** [comment]
We need to name attacks well.  We also need to classify them first.  An "iterator maximum" is a type of "DoS with Block Gas Limit" but that shouldn't limit the thinking.  If we do want to give this specific instance a name, I'm not sure if "iterator maximum" is the term people are going to use.

**Comment by nemild** [comment]
That's right, I don't know what term the community will use - so we just stick with whatever you think that is. If it's a *Denial of Service with Block Gas Limit*, that's fine with me (it just feels long).

**Comment by ethers** [comment]
Normally it might just be called a DoS.  I suggested the extension for more clarity.  (I think the term is reasonable given its current security meanings)

**Comment by simondlr** [comment]
I'd stick with DoS with Block Gas Limit for now. Iterator maximum would be a class of this attack.

**Comment by nemild** [comment]
@ethers Is the reason to close this without merging because of the wrong name? This has an example and a short description that I'd like to keep, if possible - regardless of what the final name is.

**Comment by ethers** [comment]
Hi @nemild The example is still there; the improvements in PR don't affect the meaning of the code.  There was also a little more explanation about the BGL that this PR removed thats seems would be helpful.  I agree the code tweaks are better and some other suggestions, but it's too fiddly and I think a new PR for the parts you want to modify about this would be clearer...

**Pull request closed without merging**
