### PR TITLE
Reorder the attacks and recommendations sections

### PR DESCRIPTION
**Pull request by yippee-ki-yay**
#112 @maurelian Saw that the last person got bored so added a quick pull req. let me know if anything needs to be fixed

### CODE REVIEW

**Comment by yippee-ki-yay** [comment]
Shows the commits from the last PR i did not sure if that's an issue

**Comment by owocki** [comment]
@yippee-ki-yay thanks for claiming this.  @maurelian let me know how the PR looks!

**Comment by maurelian** [comment]
LGTM TY!

**Comment by yippee-ki-yay** [comment]
Great thanks guys!

**Pull request merged**
