### PR TITLE
Added additional sections (reviewers, documentation, contributing, disclaimer)

### PR DESCRIPTION
**Pull request by nemild**

### CODE REVIEW

**Comment by simondlr** [comment]
Might be useful to have something like this, but where would one draw the line? Might become silly and useless if everyone just starts adding their names to this? Definitely something to think about though.

**Comment by nemild** [comment]
I added in a section on documentation and on contributing.

**Comment by nemild** [comment]
Also, for your feedback on reviewers, if you are approving reviewers (by approving pull request) - then I don't think that list will be abnormally large - and you can select who will be included.

The main point is that a document for improving security will only be trusted it if many respected members of the community approve of it (and even then, there'll be issues, as Ethereum and Solidity are new).

By adding a list of people who review it, it can enable a few things:

- Force the original writers to solicit direct feedback from respected and knowledgeable community members, to ensure the accuracy and exhaustiveness of what they've written
- Require a degree of rigor in the review, as a name will be explicitly listed
- Highlight to community that this document is accurate - and reflects many techniques that reflect best practice

**Comment by simondlr** [comment]
> you can select who will be included

I don't want that job. I suspect people can just say on Twitter or Reddit that they've reviewed it?

But I'm not fully against it. Let's merge it in, and if it becomes unwieldy, let's remove it. I suggest, along with timestamp, we put in commit logs to show what version of the doc the reviewer read?

@ethers thoughts?

**Comment by nemild** [comment]
@simondlr That should be great, I'm totally open to removing if it becomes an issue.

**Pull request merged**
