### PR TITLE
Edited speed bumps - edited text, added example

### PR DESCRIPTION
**Pull request by nemild**

### CODE REVIEW

**Comment by simondlr** [comment]
This has several compilation errors in browser-solidity. Please fix them.

**Comment by nemild** [comment]
Yup, I totally agree. I should always run everything through the compiler. Should be fixed now.

**Comment by simondlr** [comment]
Looks good, but there's another indentation issue in the withdraw() function (inside the if statement).

**Comment by nemild** [comment]
Fixed.

**Comment by ethers** [comment]
merged; example has no errors in browser-solidity

**Pull request merged**
